# Generated by Django 2.1.1 on 2018-09-02 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_auto_20180902_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportImageConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_img', models.FileField(null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport_img_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
