# Generated by Django 2.1.1 on 2018-09-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_passportimageconfirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passportimageconfirmation',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='passport_img',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.DeleteModel(
            name='PassportImageConfirmation',
        ),
    ]
